
# {string.unique}:
#   name:{string.like(title-of-the-page).isRequired}
#   source:{oneOf(github|lark|gitlab).isRequired}
#   link:{string.like(zoolsher/tiny-blog-test:README.md).isRequired}
#   time:{string.like(2017-6-6)}
#   auther:{string.like(zoolsher)}
#   auther-link:{string.like(url-to-your-profile)}
#   desc:{string}

mole:
  name: 地鼠和它们的地洞
  source: github
  auther: yiiqii
  time: 2017-08-02
  auther-link: https://github.com/yiiqii
  link: yiiqii/blog:lab/tiny/1_mole_hole.md
  desc: 打地鼠这类小游戏大家应该都多多少少玩过，各种版本数不胜数，今天，就来用 Tiny.js 给大家讲一讲地鼠是如何打洞的。

snake:
  name: Tiny.js 开发感受(贪吃蛇)
  source: github
  auther: Zz0819
  time: 2017-07-28
  auther-link: https://github.com/Zz0819
  link: Zz0819/snake:tutorial.md
  desc: 初次体验Tiny开发，整体开发还是挺顺利的，没有什么特别难懂的地方。有不明白的多拿捏一下文档，就能发现解决办法。

doodle:
  name: 【上手】用 Tiny 写个 DoodleJump 给你看
  source: github
  auther: zoolsher
  auther-link: https://github.com/zoolsher
  time: 2017-07-27
  link: zoolsher/doodle-jump:doodle.md
  desc: 用 Tiny 写个 DoodleJump 给你看。碰撞 + 简单的运动系统 + 重力感应事件 + 键盘事件 + ES5

bone:
  name: 「Tiny.js 实战」骨骼动画
  source: github
  auther: qingyangmoke
  auther-link: https://github.com/qingyangmoke
  time: 2017-07-27
  link: qingyangmoke/blogs:tinyjs/dragonbones.md
  desc: 使用 Tiny.js 也能轻松做骨骼动画

contribute:
  name: 欢迎投稿
  source: github
  auther: tinyjs
  time: 2017-06-15
  auther-link: https://github.com/ant-tinyjs
  link: yiiqii/blog:lab/tiny/0_contribute.md
  desc: 梧桐树上憩凤凰，来着不拒
